// Writes the SQL that replaces the fee and validity rows in the live database with the gazetted
// schedules in src/services/rulesEngine.ts. Run: npx tsx scripts/build-rules-migration.ts <out.sql>
import { writeFileSync } from 'node:fs';
import { DEFAULT_FEE_RULES, DEFAULT_VALIDITY_RULES } from '../src/services/rulesEngine';

const q = (v: string) => `'${v.replace(/'/g, "''")}'`;
const j = (o: unknown) => `${q(JSON.stringify(o))}::jsonb`;
const ids = DEFAULT_FEE_RULES.map(r => q(r.id)).join(', ');
const out = [
  '-- Fees: Schedule IX of the Delhi and Gujarat Legal Metrology (Enforcement) Rules, 2011 (replaces demo values).',
  '-- Validity: Legal Metrology (General) Rules, 2011, rule 27. Generated by scripts/build-rules-migration.ts.',
  'begin;',
  `delete from public.fee_rules where id not in (${ids}) and id not like '%-OVR';`,
  `insert into public.fee_rules (id, jurisdiction, data) values\n${DEFAULT_FEE_RULES.map(r => `  (${q(r.id)}, ${q(r.jurisdiction)}, ${j(r)})`).join(',\n')}\non conflict (id) do update set jurisdiction = excluded.jurisdiction, data = excluded.data;`,
  `insert into public.validity_rules (id, data) values\n${DEFAULT_VALIDITY_RULES.map(r => `  (${q(r.category)}, ${j(r)})`).join(',\n')}\non conflict (id) do update set data = excluded.data;`,
  'commit;',
];
writeFileSync(process.argv[2], out.join('\n') + '\n');
console.log('fee rows', DEFAULT_FEE_RULES.length, 'validity rows', DEFAULT_VALIDITY_RULES.length);
