// Generates supabase/seed.sql from the app's seed data, so the live database starts with the
// same demo records the prototype shows. Run: npx tsx scripts/build-seed-sql.ts
import { writeFileSync } from 'node:fs';
import {
  DEMO_USERS, INITIAL_INSTRUMENTS, INITIAL_APPLICATIONS, INITIAL_CERTIFICATES, INITIAL_INSPECTIONS,
  INITIAL_STAMPINGS, INITIAL_ENFORCEMENT_CASES, INITIAL_AUDIT_LOGS, INITIAL_NOTIFICATIONS,
} from '../src/data/seedData';
import { SEED_SIGNATURES } from '../src/data/seedSignatures';
import { DEFAULT_FEE_RULES, DEFAULT_VALIDITY_RULES, stateCode } from '../src/services/rulesEngine';
import { buildVerifyUrl } from '../src/services/certSigning';
import { DEMO_PASSWORD, PRODUCTION_ORIGIN } from '../src/config/cloud';

const q = (v: unknown) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const j = (o: unknown) => `${q(JSON.stringify(o))}::jsonb`;
const out: string[] = ['-- Generated by scripts/build-seed-sql.ts. Safe to re-run.', 'begin;'];

const upsert = (table: string, cols: string[], rows: unknown[][]) => {
  if (!rows.length) return;
  out.push(`insert into public.${table} (${cols.join(', ')}) values\n${rows.map(r => `  (${r.join(', ')})`).join(',\n')}\non conflict (id) do update set data = excluded.data;`);
};

upsert('profiles', ['id', 'email', 'role', 'state', 'district', 'data'],
  DEMO_USERS.map(u => [q(u.id), q(u.email), q(u.role), q(u.state), q(u.district), j({ ...u, accountType: 'DEMO' })]));
out.push(`insert into public.demo_accounts (email, profile_id) values\n${DEMO_USERS.map(u => `  (${q(u.email)}, ${q(u.id)})`).join(',\n')}\non conflict (email) do nothing;`);

// Evaluator logins (pre-confirmed). The trigger links each to its profile by email.
for (const u of DEMO_USERS) {
  out.push(`do $$ declare uid uuid; begin
  select id into uid from auth.users where lower(email) = lower(${q(u.email)});
  if uid is null then
    uid := gen_random_uuid();
    insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token)
    values ('00000000-0000-0000-0000-000000000000', uid, 'authenticated', 'authenticated', ${q(u.email)}, crypt(${q(DEMO_PASSWORD)}, gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '');
    insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
    values (gen_random_uuid(), uid, uid::text, jsonb_build_object('sub', uid::text, 'email', ${q(u.email)}, 'email_verified', true), 'email', now(), now(), now());
  end if;
  update public.profiles set auth_id = uid where id = ${q(u.id)};
end $$;`);
}

upsert('instruments', ['id', 'state', 'district', 'owner_id', 'data'],
  INITIAL_INSTRUMENTS.map(i => [q(i.id), q(i.state), q(i.district), q(i.ownerId), j(i)]));
upsert('applications', ['id', 'state', 'district', 'applicant_id', 'assigned_to_id', 'instrument_id', 'status', 'data'],
  INITIAL_APPLICATIONS.map(a => [q(a.id), q(a.state), q(a.district), q(a.applicantId), q(a.assignedToId), q(a.instrumentId), q(a.status), j(a)]));
const instState = new Map(INITIAL_INSTRUMENTS.map(i => [i.id, i.state]));
upsert('inspections', ['id', 'application_id', 'instrument_id', 'inspector_id', 'state', 'data'],
  INITIAL_INSPECTIONS.map(i => [q(i.id), q(i.applicationId), q(i.instrumentId), q(i.inspectorId), q(instState.get(i.instrumentId) || 'Delhi'), j(i)]));
upsert('stampings', ['id', 'instrument_id', 'state', 'data'],
  INITIAL_STAMPINGS.map(s => [q(s.id), q(s.instrumentId), q(instState.get(s.instrumentId) || 'Delhi'), j(s)]));
upsert('certificates', ['id', 'cert_no', 'instrument_id', 'state', 'status', 'data'],
  INITIAL_CERTIFICATES.map(c => {
    const sig = SEED_SIGNATURES[c.id];
    const data = sig
      ? { ...c, signatureStatus: 'SIGNED', signedPayload: sig.p, signature: sig.s, signingKid: sig.kid, signedAt: sig.iat, qrPayloadUrl: buildVerifyUrl(PRODUCTION_ORIGIN, c.certificateNumber, sig.p, sig.s) }
      : { ...c, signatureStatus: 'LEGACY_UNSIGNED', qrPayloadUrl: buildVerifyUrl(PRODUCTION_ORIGIN, c.certificateNumber) };
    return [q(c.id), q(c.certificateNumber), q(c.instrumentId), q(c.state), q(c.status), j(data)];
  }));
upsert('enforcement_cases', ['id', 'instrument_id', 'state', 'data'],
  INITIAL_ENFORCEMENT_CASES.map(e => [q(e.id), q(e.instrumentId), q(e.state), j(e)]));
upsert('audit_logs', ['id', 'actor_id', 'entity_id', 'state', 'data'],
  INITIAL_AUDIT_LOGS.map(l => [q(l.id), q(l.actorId), q(l.entityId), q(DEMO_USERS.find(u => u.id === l.actorId)?.state || null), j(l)]));
upsert('notifications', ['id', 'recipient_id', 'recipient_role', 'data'],
  INITIAL_NOTIFICATIONS.map(n => [q(n.id), q(n.recipientId), q(n.recipientRole), j(n)]));
upsert('fee_rules', ['id', 'jurisdiction', 'data'], DEFAULT_FEE_RULES.map(r => [q(r.id), q(r.jurisdiction), j(r)]));
upsert('validity_rules', ['id', 'data'], DEFAULT_VALIDITY_RULES.map(r => [q(r.category), j(r)]));

// Counters start above the highest seeded number so new ids never collide.
const counters = new Map<string, number>();
const bump = (id: string) => {
  const m = id.match(/^(.*?)(\d+)$/);
  if (!m) return;
  counters.set(m[1], Math.max(counters.get(m[1]) || 0, parseInt(m[2], 10)));
};
[...INITIAL_INSTRUMENTS, ...INITIAL_APPLICATIONS, ...INITIAL_INSPECTIONS, ...INITIAL_STAMPINGS, ...INITIAL_ENFORCEMENT_CASES].forEach(r => bump(r.id));
INITIAL_CERTIFICATES.forEach(c => bump(c.id));
for (const st of ['Delhi', 'Gujarat', 'Maharashtra']) {
  const code = stateCode(st);
  if (!counters.has(`LM-${code}-2026-`)) counters.set(`LM-${code}-2026-`, 0);
}
out.push(`insert into public.id_counters (prefix, last) values\n${[...counters].map(([p, n]) => `  (${q(p)}, ${n})`).join(',\n')}\non conflict (prefix) do update set last = greatest(public.id_counters.last, excluded.last);`);

out.push('commit;');
writeFileSync('supabase/seed.sql', out.join('\n\n') + '\n');
console.log('seed.sql written:', out.length, 'statements');
