// Signs the seeded sample certificates with the issuing key, so the demo QR codes verify on any phone.
// Usage: npx tsx scripts/sign-seed-certificates.ts   (reads CERT_SIGNING_PRIVATE_KEY from .env)
import { readFileSync, writeFileSync } from 'node:fs';
import { INITIAL_CERTIFICATES } from '../src/data/seedData';
import { fieldsFromCertificate } from '../src/services/certSigning';
// @ts-expect-error plain JS module
import { signPayload, validatePayload, keyFromBase64 } from '../api/sign.js';

const env = Object.fromEntries(
  readFileSync('.env', 'utf8').split(/\r?\n/).filter(l => l.includes('=') && !l.startsWith('#'))
    .map(l => [l.slice(0, l.indexOf('=')).trim(), l.slice(l.indexOf('=') + 1).trim()]),
);
const key = keyFromBase64(env.CERT_SIGNING_PRIVATE_KEY);
const kid = env.CERT_SIGNING_KEY_ID || 'tula-demo-2026-09';

const out: Record<string, { p: string; s: string; kid: string; iat: string }> = {};
for (const c of INITIAL_CERTIFICATES) {
  const auth = /GATC|Test Cent/i.test(c.issuingAuthority) ? 'GATC' : 'LMO';
  const fields = fieldsFromCertificate(c, auth);
  const problem = validatePayload({ ...fields, dt: c.verificationDate });
  if (problem && !problem.includes('future')) throw new Error(`${c.id}: ${problem}`);
  const { p, s } = signPayload(fields, key, kid, c.issuedAt);
  out[c.id] = { p, s, kid, iat: c.issuedAt };
}
writeFileSync('src/data/seedSignatures.ts',
  `// Generated by scripts/sign-seed-certificates.ts. Signatures of the seeded sample certificates.\n` +
  `export const SEED_SIGNATURES: Record<string, { p: string; s: string; kid: string; iat: string }> = ${JSON.stringify(out, null, 2)};\n`);
console.log('signed', Object.keys(out).length, 'certificates');
